import 'package:permission_scanner/models/permission_info.dart';

final Map<String, PermissionInfo> permissionDatabase = {
  'android.permission.CAMERA': PermissionInfo(
    name: 'android.permission.CAMERA',
    displayName: 'Camera',
    description: 'Access to device camera',
    group: 'Camera',
    isDangerous: true,
  ),
  'android.permission.RECORD_AUDIO': PermissionInfo(
    name: 'android.permission.RECORD_AUDIO',
    displayName: 'Microphone',
    description: 'Record audio from microphone',
    group: 'Microphone',
    isDangerous: true,
  ),
  'android.permission.READ_CONTACTS': PermissionInfo(
    name: 'android.permission.READ_CONTACTS',
    displayName: 'Read Contacts',
    description: 'Access to contact information',
    group: 'Contacts',
    isDangerous: true,
  ),
  'android.permission.WRITE_CONTACTS': PermissionInfo(
    name: 'android.permission.WRITE_CONTACTS',
    displayName: 'Write Contacts',
    description: 'Modify contact information',
    group: 'Contacts',
    isDangerous: true,
  ),
  'android.permission.ACCESS_FINE_LOCATION': PermissionInfo(
    name: 'android.permission.ACCESS_FINE_LOCATION',
    displayName: 'Precise Location',
    description: 'Access precise location (GPS)',
    group: 'Location',
    isDangerous: true,
  ),
  'android.permission.ACCESS_COARSE_LOCATION': PermissionInfo(
    name: 'android.permission.ACCESS_COARSE_LOCATION',
    displayName: 'Approximate Location',
    description: 'Access approximate location (Network)',
    group: 'Location',
    isDangerous: true,
  ),
  'android.permission.ACCESS_BACKGROUND_LOCATION': PermissionInfo(
    name: 'android.permission.ACCESS_BACKGROUND_LOCATION',
    displayName: 'Background Location',
    description: 'Access location while the app is not open',
    group: 'Location',
    isDangerous: true,
  ),
  'android.permission.READ_SMS': PermissionInfo(
    name: 'android.permission.READ_SMS',
    displayName: 'Read SMS',
    description: 'Read text messages',
    group: 'SMS',
    isDangerous: true,
  ),
  'android.permission.SEND_SMS': PermissionInfo(
    name: 'android.permission.SEND_SMS',
    displayName: 'Send SMS',
    description: 'Send text messages',
    group: 'SMS',
    isDangerous: true,
  ),
  'android.permission.RECEIVE_SMS': PermissionInfo(
    name: 'android.permission.RECEIVE_SMS',
    displayName: 'Receive SMS',
    description: 'Receive incoming text messages',
    group: 'SMS',
    isDangerous: true,
  ),
  'android.permission.RECEIVE_MMS': PermissionInfo(
    name: 'android.permission.RECEIVE_MMS',
    displayName: 'Receive MMS',
    description: 'Receive multimedia messages',
    group: 'SMS',
    isDangerous: true,
  ),
  'android.permission.READ_CALL_LOG': PermissionInfo(
    name: 'android.permission.READ_CALL_LOG',
    displayName: 'Read Call Log',
    description: 'Access call history',
    group: 'Call Log',
    isDangerous: true,
  ),
  'android.permission.WRITE_CALL_LOG': PermissionInfo(
    name: 'android.permission.WRITE_CALL_LOG',
    displayName: 'Write Call Log',
    description: 'Modify call history',
    group: 'Call Log',
    isDangerous: true,
  ),
  'android.permission.READ_EXTERNAL_STORAGE': PermissionInfo(
    name: 'android.permission.READ_EXTERNAL_STORAGE',
    displayName: 'Read Storage',
    description: 'Access files on device storage',
    group: 'Storage',
    isDangerous: true,
  ),
  'android.permission.WRITE_EXTERNAL_STORAGE': PermissionInfo(
    name: 'android.permission.WRITE_EXTERNAL_STORAGE',
    displayName: 'Write Storage',
    description: 'Modify files on device storage',
    group: 'Storage',
    isDangerous: true,
  ),
  'android.permission.READ_MEDIA_IMAGES': PermissionInfo(
    name: 'android.permission.READ_MEDIA_IMAGES',
    displayName: 'Photos',
    description: 'Read photos and images',
    group: 'Media',
    isDangerous: true,
  ),
  'android.permission.READ_MEDIA_VIDEO': PermissionInfo(
    name: 'android.permission.READ_MEDIA_VIDEO',
    displayName: 'Videos',
    description: 'Read videos',
    group: 'Media',
    isDangerous: true,
  ),
  'android.permission.READ_MEDIA_AUDIO': PermissionInfo(
    name: 'android.permission.READ_MEDIA_AUDIO',
    displayName: 'Audio',
    description: 'Read music and audio files',
    group: 'Media',
    isDangerous: true,
  ),
  'android.permission.READ_PHONE_STATE': PermissionInfo(
    name: 'android.permission.READ_PHONE_STATE',
    displayName: 'Read Phone State',
    description: 'Access phone state and call information',
    group: 'Phone',
    isDangerous: true,
  ),
  'android.permission.CALL_PHONE': PermissionInfo(
    name: 'android.permission.CALL_PHONE',
    displayName: 'Make Calls',
    description: 'Make phone calls directly',
    group: 'Phone',
    isDangerous: true,
  ),
  'android.permission.USE_SIP': PermissionInfo(
    name: 'android.permission.USE_SIP',
    displayName: 'Use SIP',
    description: 'Make SIP calls',
    group: 'Phone',
    isDangerous: true,
  ),
  'android.permission.READ_PHONE_NUMBERS': PermissionInfo(
    name: 'android.permission.READ_PHONE_NUMBERS',
    displayName: 'Phone Number',
    description: 'Read the device phone number',
    group: 'Phone',
    isDangerous: true,
  ),
  'android.permission.ANSWER_PHONE_CALLS': PermissionInfo(
    name: 'android.permission.ANSWER_PHONE_CALLS',
    displayName: 'Answer Calls',
    description: 'Answer incoming phone calls',
    group: 'Phone',
    isDangerous: true,
  ),
  'android.permission.BLUETOOTH_SCAN': PermissionInfo(
    name: 'android.permission.BLUETOOTH_SCAN',
    displayName: 'Nearby Devices Scan',
    description: 'Scan for nearby Bluetooth devices',
    group: 'Nearby Devices',
    isDangerous: true,
  ),
  'android.permission.BLUETOOTH_CONNECT': PermissionInfo(
    name: 'android.permission.BLUETOOTH_CONNECT',
    displayName: 'Nearby Devices Connect',
    description: 'Connect to nearby Bluetooth devices',
    group: 'Nearby Devices',
    isDangerous: true,
  ),
  'android.permission.BODY_SENSORS': PermissionInfo(
    name: 'android.permission.BODY_SENSORS',
    displayName: 'Body Sensors',
    description: 'Read health sensor data',
    group: 'Sensors',
    isDangerous: true,
  ),
  'android.permission.ACTIVITY_RECOGNITION': PermissionInfo(
    name: 'android.permission.ACTIVITY_RECOGNITION',
    displayName: 'Physical Activity',
    description: 'Detect walking, running, driving, and similar activity',
    group: 'Sensors',
    isDangerous: true,
  ),
  'android.permission.READ_CALENDAR': PermissionInfo(
    name: 'android.permission.READ_CALENDAR',
    displayName: 'Read Calendar',
    description: 'Read calendar events',
    group: 'Calendar',
    isDangerous: true,
  ),
  'android.permission.WRITE_CALENDAR': PermissionInfo(
    name: 'android.permission.WRITE_CALENDAR',
    displayName: 'Write Calendar',
    description: 'Create or change calendar events',
    group: 'Calendar',
    isDangerous: true,
  ),
  'android.permission.POST_NOTIFICATIONS': PermissionInfo(
    name: 'android.permission.POST_NOTIFICATIONS',
    displayName: 'Notifications',
    description: 'Send notifications',
    group: 'Notifications',
    isDangerous: true,
  ),
  'android.permission.INTERNET': PermissionInfo(
    name: 'android.permission.INTERNET',
    displayName: 'Internet',
    description: 'Access internet connection',
    group: 'Network',
    isDangerous: false,
  ),
  'android.permission.ACCESS_NETWORK_STATE': PermissionInfo(
    name: 'android.permission.ACCESS_NETWORK_STATE',
    displayName: 'Network State',
    description: 'Check network connectivity',
    group: 'Network',
    isDangerous: false,
  ),
  'android.permission.VIBRATE': PermissionInfo(
    name: 'android.permission.VIBRATE',
    displayName: 'Vibration',
    description: 'Control device vibration',
    group: 'Vibration',
    isDangerous: false,
  ),
  'android.permission.WAKE_LOCK': PermissionInfo(
    name: 'android.permission.WAKE_LOCK',
    displayName: 'Wake Lock',
    description: 'Prevent device from sleeping',
    group: 'Device Power',
    isDangerous: false,
  ),
  'android.permission.RECEIVE_BOOT_COMPLETED': PermissionInfo(
    name: 'android.permission.RECEIVE_BOOT_COMPLETED',
    displayName: 'Start on Boot',
    description: 'Run code after the phone restarts',
    group: 'Background',
    isDangerous: false,
  ),
  'android.permission.SYSTEM_ALERT_WINDOW': PermissionInfo(
    name: 'android.permission.SYSTEM_ALERT_WINDOW',
    displayName: 'Display Over Apps',
    description: 'Show windows over other apps',
    group: 'Overlay',
    isDangerous: false,
  ),
  'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': PermissionInfo(
    name: 'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS',
    displayName: 'Ignore Battery Optimizations',
    description: 'Ask Android to keep the app running in the background',
    group: 'Background',
    isDangerous: false,
  ),
  'android.permission.FOREGROUND_SERVICE': PermissionInfo(
    name: 'android.permission.FOREGROUND_SERVICE',
    displayName: 'Foreground Service',
    description: 'Run an ongoing service with a persistent notification',
    group: 'Background',
    isDangerous: false,
  ),
  'android.permission.SCHEDULE_EXACT_ALARM': PermissionInfo(
    name: 'android.permission.SCHEDULE_EXACT_ALARM',
    displayName: 'Exact Alarms',
    description: 'Wake the app at exact times',
    group: 'Background',
    isDangerous: false,
  ),
  'com.google.android.gms.permission.AD_ID': PermissionInfo(
    name: 'com.google.android.gms.permission.AD_ID',
    displayName: 'Advertising ID',
    description: 'Read the Google advertising identifier',
    group: 'Tracking',
    isDangerous: false,
  ),
};

const List<String> dangerousPermissions = [
  'android.permission.CAMERA',
  'android.permission.RECORD_AUDIO',
  'android.permission.READ_CONTACTS',
  'android.permission.WRITE_CONTACTS',
  'android.permission.ACCESS_FINE_LOCATION',
  'android.permission.ACCESS_COARSE_LOCATION',
  'android.permission.ACCESS_BACKGROUND_LOCATION',
  'android.permission.READ_SMS',
  'android.permission.SEND_SMS',
  'android.permission.RECEIVE_SMS',
  'android.permission.RECEIVE_MMS',
  'android.permission.READ_CALL_LOG',
  'android.permission.WRITE_CALL_LOG',
  'android.permission.READ_EXTERNAL_STORAGE',
  'android.permission.WRITE_EXTERNAL_STORAGE',
  'android.permission.READ_MEDIA_IMAGES',
  'android.permission.READ_MEDIA_VIDEO',
  'android.permission.READ_MEDIA_AUDIO',
  'android.permission.READ_PHONE_STATE',
  'android.permission.CALL_PHONE',
  'android.permission.USE_SIP',
  'android.permission.READ_PHONE_NUMBERS',
  'android.permission.ANSWER_PHONE_CALLS',
  'android.permission.BLUETOOTH_SCAN',
  'android.permission.BLUETOOTH_CONNECT',
  'android.permission.BODY_SENSORS',
  'android.permission.ACTIVITY_RECOGNITION',
  'android.permission.READ_CALENDAR',
  'android.permission.WRITE_CALENDAR',
  'android.permission.POST_NOTIFICATIONS',
];

/// Developer-only permissions that are hidden by default
const List<String> developerOnlyPermissions = [
  'android.permission.AD_SERVICES_CONFIG',
  'com.android.permission.INSTALL_APPS',
  'android.permission.QUERY_ALL_PACKAGES',
  'android.permission.MANAGE_EXTERNAL_STORAGE',
  'android.permission.BIND_ACCESSIBILITY_SERVICE',
  'android.permission.CHANGE_NETWORK_STATE',
  'android.permission.CHANGE_WIFI_STATE',
  'android.permission.DELETE_PACKAGES',
  'android.permission.SYSTEM_ALERT_WINDOW',
  'android.permission.USE_CREDENTIALS',
];
