import 'package:permission_scanner/models/permission_info.dart';

final Map<String, PermissionInfo> permissionDatabase = {
  'android.permission.CAMERA': PermissionInfo(
    name: 'android.permission.CAMERA',
    displayName: 'Camera',
    description: 'Access to device camera',
    group: 'Camera',
    isDangerous: true,
  ),
  'android.permission.RECORD_AUDIO': PermissionInfo(
    name: 'android.permission.RECORD_AUDIO',
    displayName: 'Microphone',
    description: 'Record audio from microphone',
    group: 'Microphone',
    isDangerous: true,
  ),
  'android.permission.READ_CONTACTS': PermissionInfo(
    name: 'android.permission.READ_CONTACTS',
    displayName: 'Read Contacts',
    description: 'Access to contact information',
    group: 'Contacts',
    isDangerous: true,
  ),
  'android.permission.WRITE_CONTACTS': PermissionInfo(
    name: 'android.permission.WRITE_CONTACTS',
    displayName: 'Write Contacts',
    description: 'Modify contact information',
    group: 'Contacts',
    isDangerous: true,
  ),
  'android.permission.ACCESS_FINE_LOCATION': PermissionInfo(
    name: 'android.permission.ACCESS_FINE_LOCATION',
    displayName: 'Precise Location',
    description: 'Access precise location (GPS)',
    group: 'Location',
    isDangerous: true,
  ),
  'android.permission.ACCESS_COARSE_LOCATION': PermissionInfo(
    name: 'android.permission.ACCESS_COARSE_LOCATION',
    displayName: 'Approximate Location',
    description: 'Access approximate location (Network)',
    group: 'Location',
    isDangerous: true,
  ),
  'android.permission.READ_SMS': PermissionInfo(
    name: 'android.permission.READ_SMS',
    displayName: 'Read SMS',
    description: 'Read text messages',
    group: 'SMS',
    isDangerous: true,
  ),
  'android.permission.SEND_SMS': PermissionInfo(
    name: 'android.permission.SEND_SMS',
    displayName: 'Send SMS',
    description: 'Send text messages',
    group: 'SMS',
    isDangerous: true,
  ),
  'android.permission.READ_CALL_LOG': PermissionInfo(
    name: 'android.permission.READ_CALL_LOG',
    displayName: 'Read Call Log',
    description: 'Access call history',
    group: 'Call Log',
    isDangerous: true,
  ),
  'android.permission.WRITE_CALL_LOG': PermissionInfo(
    name: 'android.permission.WRITE_CALL_LOG',
    displayName: 'Write Call Log',
    description: 'Modify call history',
    group: 'Call Log',
    isDangerous: true,
  ),
  'android.permission.READ_EXTERNAL_STORAGE': PermissionInfo(
    name: 'android.permission.READ_EXTERNAL_STORAGE',
    displayName: 'Read Storage',
    description: 'Access files on device storage',
    group: 'Storage',
    isDangerous: true,
  ),
  'android.permission.WRITE_EXTERNAL_STORAGE': PermissionInfo(
    name: 'android.permission.WRITE_EXTERNAL_STORAGE',
    displayName: 'Write Storage',
    description: 'Modify files on device storage',
    group: 'Storage',
    isDangerous: true,
  ),
  'android.permission.READ_PHONE_STATE': PermissionInfo(
    name: 'android.permission.READ_PHONE_STATE',
    displayName: 'Read Phone State',
    description: 'Access phone state and call information',
    group: 'Phone',
    isDangerous: true,
  ),
  'android.permission.CALL_PHONE': PermissionInfo(
    name: 'android.permission.CALL_PHONE',
    displayName: 'Make Calls',
    description: 'Make phone calls directly',
    group: 'Phone',
    isDangerous: true,
  ),
  'android.permission.USE_SIP': PermissionInfo(
    name: 'android.permission.USE_SIP',
    displayName: 'Use SIP',
    description: 'Make SIP calls',
    group: 'Phone',
    isDangerous: true,
  ),
  'android.permission.INTERNET': PermissionInfo(
    name: 'android.permission.INTERNET',
    displayName: 'Internet',
    description: 'Access internet connection',
    group: 'Network',
    isDangerous: false,
  ),
  'android.permission.ACCESS_NETWORK_STATE': PermissionInfo(
    name: 'android.permission.ACCESS_NETWORK_STATE',
    displayName: 'Network State',
    description: 'Check network connectivity',
    group: 'Network',
    isDangerous: false,
  ),
  'android.permission.VIBRATE': PermissionInfo(
    name: 'android.permission.VIBRATE',
    displayName: 'Vibration',
    description: 'Control device vibration',
    group: 'Vibration',
    isDangerous: false,
  ),
  'android.permission.WAKE_LOCK': PermissionInfo(
    name: 'android.permission.WAKE_LOCK',
    displayName: 'Wake Lock',
    description: 'Prevent device from sleeping',
    group: 'Device Power',
    isDangerous: false,
  ),
};

const List<String> dangerousPermissions = [
  'android.permission.CAMERA',
  'android.permission.RECORD_AUDIO',
  'android.permission.READ_CONTACTS',
  'android.permission.WRITE_CONTACTS',
  'android.permission.ACCESS_FINE_LOCATION',
  'android.permission.ACCESS_COARSE_LOCATION',
  'android.permission.READ_SMS',
  'android.permission.SEND_SMS',
  'android.permission.READ_CALL_LOG',
  'android.permission.WRITE_CALL_LOG',
  'android.permission.READ_EXTERNAL_STORAGE',
  'android.permission.WRITE_EXTERNAL_STORAGE',
  'android.permission.READ_PHONE_STATE',
  'android.permission.CALL_PHONE',
  'android.permission.USE_SIP',
];
